

const vscode = acquireVsCodeApi();

const initial = window.__MARKDOWN_STUDIO_INITIAL_STATE__ || {};

const persistedState = vscode.getState ? (vscode.getState() || {}) : {};

const state = {
  uri: initial.uri || '',
  fileName: initial.fileName || 'document.md',
  documentKind: initial.documentKind || 'markdown',
  markdown: initial.markdown || '',
  committedMarkdown: initial.markdown || '',
  markdownHash: initial.markdownHash || '',
  previewOnly: !!initial.previewOnly,
  documentDeleted: false,
  autoSave: initial.autoSave !== false,
  previewEditEnabled: !!initial.previewEditEnabled,
  theme: persistedState.theme || initial.theme || 'reader-light',
  language: persistedState.language || initial.language || 'en',
  layout: Object.assign({ outline: 300, source: 580 }, persistedState.layout || {}),
  outlineFilesHeight: Number(persistedState.outlineFilesHeight) || 190,
  expandedFolders: persistedState.expandedFolders && typeof persistedState.expandedFolders === 'object' ? persistedState.expandedFolders : {},
  sourceCollapsed: !initial.previewOnly && (typeof persistedState.sourceCollapsed === 'boolean' ? persistedState.sourceCollapsed : true),
  readerFontSize: Number(persistedState.readerFontSize || initial.readerFontSize) || 15,
  markdownFiles: Array.isArray(initial.markdownFiles) ? initial.markdownFiles : [],
  blocks: [],
  refs: new Map(),
  sectionPreviews: new Map(),
  imageMap: new Map(),
  blockElements: [],
  blockTops: [],
  blockHeights: [],
  blockTopByIndex: new Map(),
  blockElementByIndex: new Map(),
  blockElementBySourceStart: new Map(),
  renderTimer: null,
  renderVersion: 0,
  previewMetricsDirty: true,
  previewResizeObserver: null,
  observedPreviewBlocks: new Set(),
  richRendererObserver: null,
  richRendererQueue: new Set(),
  richRendererTimer: null,
  richRendererRunning: false,
  previewScrolling: false,
  previewScrollIdleTimer: null,
  sourceAxisPending: false,
  saveTimer: null,
  saveSeq: 0,
  pendingMarkdownSaves: new Map(),
  patchTimer: null,
  hoverTimer: null,
  previewScrollRaf: 0,
  previewRepaintRaf: 0,
  previewRepaintTimer: null,
  noteMarginRaf: 0,
  noteMarginTimer: null,
  lastNoteMarginRender: 0,
  bookmarkMarkersRaf: 0,
  railPreviewRaf: 0,
  sourceAxisRaf: 0,
  sourceAxisVisibleRaf: 0,
  sourceAxisTimer: null,
  sourceAxisGeometryRaf: 0,
  sourceAxisGeometryTimer: null,
  sourceAxisGeometryPending: false,
  sourceAxisActiveRaf: 0,
  sourceAxisBuildVersion: 0,
  sourceAxisBuildTimer: null,
  sourceAxisItems: [],
  sourceAxisVisibleRange: '',
  sourceAxisMarkers: new Map(),
  activeSourceAxisMarker: null,
  activeSourceAxisIndex: '',
  lastRailPreviewEvent: null,
  railDrag: null,
  railClickSuppressed: false,
  railClickSuppressTimer: null,
  scrollDebounceTimer: null,
  scrollLockTimer: null,
  scrollSyncLock: null,
  activeBlockIndex: null,
  outlineMode: 'preview',
  readingHistory: [],
  readingHistoryIndex: -1,
  readingHistoryTimer: null,
  readingProgress: initial.readingProgress || null,
  readingProgressSaveTimer: null,
  searchQuery: '',
  searchMatches: [],
  searchIndex: -1,
  searchActiveElement: null,
  tableLayouts: initial.tableLayouts && typeof initial.tableLayouts === 'object' ? initial.tableLayouts : {},
  tableLayoutsSaveTimer: null,
  lastSavedReadingProgress: '',
  pendingDocumentSwitch: null,
  markdownFilesSignature: '',
  annotations: Array.isArray(initial.annotations) ? initial.annotations : [],
  pendingAnnotationSelection: null,
  previewContextSelection: null,
  lastPreviewCopyDetails: null,
  readingHistoryApplying: false,
  previewScrollIntent: false,
  lightboxObjectUrl: null
};

const els = {
  outlineTitle: document.getElementById('outlineTitle'),
  fileListTitle: document.getElementById('fileListTitle'),
  documentName: document.getElementById('documentName'),
  sourceTitle: document.getElementById('sourceTitle'),
  previewTitle: document.getElementById('previewTitle'),
  sourceStatus: document.getElementById('sourceStatus'),
  previewStatus: document.getElementById('previewStatus'),
  previewPane: document.querySelector('.preview-pane'),
  sourceToolbarHost: document.getElementById('sourceToolbarHost'),
  collapsedToolbarHost: document.getElementById('collapsedToolbarHost'),
  sourceActions: document.getElementById('sourceActions'),
  languageControl: document.getElementById('languageControl'),
  languageLabel: document.getElementById('languageLabel'),
  languageSelect: document.getElementById('languageSelect'),
  themeControl: document.getElementById('themeControl'),
  themeLabel: document.getElementById('themeLabel'),
  fontSizeControl: document.getElementById('fontSizeControl'),
  fontSizeLabel: document.getElementById('fontSizeLabel'),
  fontSizeSelect: document.getElementById('fontSizeSelect'),
  saveDocument: document.getElementById('saveDocument'),
  collapseMarkdown: document.getElementById('collapseMarkdown'),
  exportHtml: document.getElementById('exportHtml'),
  togglePreviewEdit: document.getElementById('togglePreviewEdit'),
  themeSelect: document.getElementById('themeSelect'),
  editor: document.getElementById('markdownEditor'),
  preview: document.getElementById('preview'),
  sourceAxis: document.getElementById('sourceAxis'),
  previewScroller: document.getElementById('previewScroller'),
  markdownFileList: document.getElementById('markdownFileList'),
  outlineSplitHandle: document.getElementById('outlineSplitHandle'),
  outlineTree: document.getElementById('outlineTree'),
  previewToc: document.getElementById('previewToc'),
  previewTocToggle: document.getElementById('previewTocToggle'),
  previewTocNav: document.getElementById('previewTocNav'),
  previewNotes: document.getElementById('previewNotes'),
  previewNotesToggle: document.getElementById('previewNotesToggle'),
  previewNotesList: document.getElementById('previewNotesList'),
  noteMarginPanel: document.getElementById('noteMarginPanel'),
  noteConnectorLayer: document.getElementById('noteConnectorLayer'),
  renderStats: document.getElementById('renderStats'),
  readingBack: document.getElementById('readingBack'),
  readingForward: document.getElementById('readingForward'),
  hovercard: document.getElementById('hovercard'),
  searchBox: document.getElementById('searchBox'),
  searchInput: document.getElementById('searchInput'),
  searchCount: document.getElementById('searchCount'),
  searchPrev: document.getElementById('searchPrev'),
  searchNext: document.getElementById('searchNext'),
  searchClose: document.getElementById('searchClose'),
  fileContextMenu: document.getElementById('fileContextMenu'),
  selectionToolbar: document.getElementById('selectionToolbar'),
  highlightSelection: document.getElementById('highlightSelection'),
  bookmarkSelection: document.getElementById('bookmarkSelection'),
  noteSelection: document.getElementById('noteSelection'),
  selectionNoteEditor: document.getElementById('selectionNoteEditor'),
  selectionNoteText: document.getElementById('selectionNoteText'),
  confirmSelectionNote: document.getElementById('confirmSelectionNote'),
  cancelSelectionNote: document.getElementById('cancelSelectionNote'),
  bookmarkRail: document.getElementById('bookmarkRail'),
  lightbox: document.getElementById('imageLightbox'),
  lightboxToolbar: document.getElementById('lightboxToolbar'),
  zoomOutButton: document.getElementById('zoomOutButton'),
  resetZoomButton: document.getElementById('resetZoomButton'),
  zoomInButton: document.getElementById('zoomInButton'),
  closeLightboxButton: document.getElementById('closeLightboxButton')
};

if (state.previewOnly) document.body.classList.add('preview-only');

const annotationBlockPattern = /(?:\r?\n){0,2}<!--\s*read-md-as-html:annotations\s*\r?\n[\s\S]*?\r?\n-->\s*$/;

export { vscode, initial, persistedState, state, els, annotationBlockPattern };
