const fs = require('node:fs/promises');
const path = require('node:path');
const esbuild = require('esbuild');

async function build() {
  const root = path.resolve(__dirname, '..');
  process.chdir(root);
  await fs.mkdir('media/vendor', { recursive: true });
  for (const [source, target] of [
    ['dompurify/dist/purify.min.js', 'purify.min.js'],
    ['marked/marked.min.js', 'marked.min.js'],
    ['turndown/dist/turndown.js', 'turndown.js'],
    ['mermaid/dist/mermaid.min.js', 'mermaid.min.js']
  ]) await fs.copyFile(path.join('node_modules', source), path.join('media/vendor', target));
  // Include lazy-loaded TeX extensions, accessibility modules and font files.
  await fs.cp('node_modules/mathjax/es5', 'media/vendor/mathjax', { recursive: true });
  for (const name of ['dompurify', 'marked', 'turndown', 'mermaid', 'mathjax']) {
    const files = await fs.readdir(`node_modules/${name}`);
    const license = files.find(file => /^licen[cs]e(?:\.|$)/i.test(file));
    const source = license ? `node_modules/${name}/${license}` : `scripts/licenses/${name}-LICENSE.txt`;
    await fs.copyFile(source, `media/vendor/${name}-LICENSE.txt`);
  }
  await esbuild.build({ entryPoints: ['webview/main.js'], bundle: true, outfile: 'media/app.js',
    platform: 'browser', target: 'chrome120', banner: { js: '// Generated by npm run build. Edit webview/ source modules.' } });
  await esbuild.build({ entryPoints: ['webview/reader.js'], bundle: true, outfile: 'media/reader.js',
    platform: 'browser', target: 'chrome120' });
  await esbuild.build({ entryPoints: ['src/extension.js'], bundle: true, outfile: 'dist/extension.cjs',
    platform: 'node', target: 'node18', external: ['vscode'] });
}

build().catch(error => { console.error(error); process.exitCode = 1; });
